---
- name: Main configuration for all hosts
  hosts: all
  become: yes
  roles:
  - repository

- name: Deploy frontend 
  hosts: frontends
  become: yes
  roles:
    - haproxy

- name: deploy aplication on app nodes
  hosts: apps
  become: yes
  roles:
    - tomcat
    - httpd
    - deploy-app

- name: deploy postgres
  become: yes
  hosts: appdbs
  roles:
  - postgresql 
  
